[env:esp32dev]
platform = espressif32 @ 6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM14
board_build.partitions = min_spiffs.csv
lib_deps =
    GyverLibs/GyverTimer
    GyverLibs/GyverButton
    GyverLibs/GyverFilters
    LiquidCrystal @ ^1.5.0
    adafruit/Adafruit AHTX0 @ ^2.0.6
    gyverlibs/Settings
    gyverlibs/WiFiConnector
    gyverlibs/GyverDS18
    ArduinoOTA