; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32 @ 6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM14
board_build.partitions = min_spiffs.csv
lib_deps = 
	GyverLibs/GyverTimer
	GyverLibs/GyverButton
	GyverLibs/GyverFilters
	LiquidCrystal @ ^1.5.0
	adafruit/Adafruit AHTX0 @ ^2.0.6
	gyverlibs/Settings
	gyverlibs/WiFiConnector
	gyverlibs/GyverDS18
	ArduinoOTA
	gyverlibs/GyverMenu@^1.0.2
